[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    adafruit/Adafruit BMP085 Library
    adafruit/Adafruit HMC5883 Unifed
    tinygpsplus
    electroniccats/MPU6050
    sandeepmistry/LoRa
monitor_speed = 115200