[env:pico]
platform = raspberrypi
board = pico
board_build.partitions = default.csv
framework = arduino
lib_deps = 
    adafruit/Adafruit BMP085 Library@^1.0.1
    adafruit/Adafruit HMC5883 Unified@^1.2.1
    mikalhart/TinyGPSPlus@^1.1.0
    electroniccats/MPU6050@^1.0.0
    sandeepmistry/LoRa@^0.8.0
    nrf24/RF24@^1.0.10
    https://github.com/arduino-libraries/MadgwickAHRS
monitor_speed = 115200
build_flags = 
    -DBOARD_NAME=\"DroneFlightController\"
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1