[env:esp32c3-rc]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
monitor_speed = 115200
upload_speed = 921600

[env:esp32-s3-rc]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:esp32c3-tx]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DRC_MODE=RC_MODE_TRANSMITTER

[env:esp32-s3-tx]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DRC_MODE=RC_MODE_TRANSMITTER
